// search
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

// app
export const SET_APP_STATUS_LOADING = 'SET_APP_STATUS_LOADING';
export const SET_APP_STATUS_READY = 'SET_APP_STATUS_READY';

// user
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_FAVORITE_TWEET = 'SET_FAVORITE_TWEET';

